# Your full site URL. Example:
# "https://<username>.neocities.org/"
baseURL = "https://siennabates.com"
languageCode = "en-us"
# Title of your site
title = "~sienna"
theme = "neofeed-theme"
# How many feed entries to load at once
paginate = 6

[taxonomies]
tag = "tags"

[author]
name = "Sienna" # Your online name
# Your profile image. External link or relative to static/. Examples:
# "https://imgur.com/123456788"
# "image/me.webp"
image = "img/me.jpg"
about = "i research security, neat"

[params]
# Name of a file in static/skins/ without the ".css" extension
skin = "macintosh"

#
# Totally optional cool stuff (see README for details)
#
# socialImage = "static/img/social.png" # site image for rich embeds
customCSS = "css/style.css" # relative to ./static/
# plausible = true
# paymentPointer = "$wallet.provider.com/myspecialid123"
# webmentionUrl = "https://webmention.io/example/webmention"
# pingbackUrl = "https://webmention.io/example/xmlrpc"
# micropubUrl = "https://example.com/.netlify/functions/micropub"
# microsubUrl = "https://aperture.p3k.io/microsub/example"

#
# For IndieAuth and the author card
#
githubuser = "siennabates"
twitteruser = "scrumdumpster69" # no @ in front
mastodon = "https://infosec.exchange/@scrumdumpster69" # full link to your instance profile

[permalinks]
# Format for feed entry links. You probably don't need to change this.
feed = "/:title/"

[outputs]
# Output formats for your feed. You probably don't need to change this.
  home = ["HTML", "JSON", "RSS"]