# Your full site URL. Example:
# "https://<username>.neocities.org/"
baseURL = "https://siennabates.com"
languageCode = "en-us"
# Title of your site
title = "~sienna"
theme = "neofeed-theme"
# How many feed entries to load at once
[pagination]
  pagerSize = 6

[taxonomies]
tag = "tags"

[params.author]
name = "Sienna" # Your online name
# Your profile image. External link or relative to static/. Examples:
# "https://imgur.com/123456788"
# "image/me.webp"
image = "img/me2.jpg"
about = "security and privacy enthusiast, researcher, AMC A-lister"

[params]
# Name of a file in static/skins/ without the ".css" extension
skin = "macintosh"

mainSections = ["blog"]

#
# Totally optional cool stuff (see README for details)
#
# socialImage = "static/img/social.png" # site image for rich embeds
customCSS = "css/style.css" # relative to ./static/
# plausible = true
# paymentPointer = "$wallet.provider.com/myspecialid123"
# webmentionUrl = "https://webmention.io/example/webmention"
# pingbackUrl = "https://webmention.io/example/xmlrpc"
# micropubUrl = "https://example.com/.netlify/functions/micropub"
# microsubUrl = "https://aperture.p3k.io/microsub/example"

#
# For IndieAuth and the author card
#
githubuser = "siennabates"
twitteruser = "scrumdumpster69" # no @ in front
mastodon = "https://infosec.exchange/@scrumdumpster69" # full link to your instance profile

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "blog/"
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "publications/"
  [[menu.main]]
    identifier = "presentations"
    name = "Presentations"
    url = "presentations/"
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "research/"
#  [[menu.main]]
#    identifier = "fashion"
#    name = "Fashion"
#    url = "fashion/"
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "resume/"
[[menu.main]]
    identifier = "certifications"
    name = "Certifications"
    url = "certifications/"


[permalinks]
# Format for feed entry links. You probably don't need to change this.
feed = "/:title/"

[outputs]
# Output formats for your feed. You probably don't need to change this.
  home = ["HTML", "JSON", "RSS"]